# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1otUuCS48Cj16XukEafmyImY1zQabnulH
"""

import matplotlib.pyplot as plt
import numpy as np
x=np.array([0,6])
y=np.array([0,250])
plt.plot(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([1,2,6,8])
y=np.array([3,8,1,10])
plt.plot(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([4,4,5,5,6,6,8])
y=np.array([3,3,4,3,5,5,6])
plt.plot(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([0,6,7])
y=np.array([0,25,6])
plt.plot(x,marker="*")
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([2,6,7])
y=np.array([0,5,6])
plt.plot(x,y,"*--r",ms=15)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x1=np.array([0,1,2,3])
y1=np.array([3,8,1,10])
x2=np.array([0,1,2,3])
y2=np.array([6,2,7,11])
plt.plot(x1,y1,x2,y2)
plt.plot(x,y,"*--r",ms=15)

plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([0,10,10,0])
y=np.array([0,0,15,15])
plt.scatter(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x1=np.array([0,1,2,3])
y1=np.array([3,8,1,10])
plt.scatter(x1,y1,color="red")
x2=np.array([0,1,2,3])
y2=np.array([6,2,7,11])
plt.scatter(x2,y2,color="green")
plt.plot(x1,y1,x2,y2)
plt.plot(x,y,"*--r",ms=15)

plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([0,10,10,0,5])
y=np.array([0,0,15,15,7])
mycolor=['red','green','purple','lime','yellow']
plt.scatter(x,y,color=mycolor)

plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([0,10,10,0,5])
y=np.array([0,0,15,15,7])
mycolor=['red','green','purple','lime','yellow']
size=[10,60,100,70,50]
plt.scatter(x,y,color=mycolor,s=size)


plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array(['A','B','C','D'])
y=np.array([3,8,1,10])
plt.bar(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array(['A','B','C','D'])
y=np.array([3,8,1,10])
plt.barh(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array(['A','B','C','D'])
y=np.array([3,8,1,10])
plt.bar(x,y,width=0.1)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([10,30,25,35])

plt.pie(x)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([10,30,25,35])
mylabels=["Ananas","Banan","Apple","Dates"]

plt.pie(x,labels=mylabels)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([10,30,25,35])
mylabels=["Ananas","Banan","Apple","Dates"]

plt.pie(x,labels=mylabels,startangle=90)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([10,30,25,35])
mylabels=["Ananas","Banan","Apple","Dates"]
myexplode=[0.2,0,0,0]
plt.pie(x,labels=mylabels,startangle=90,explode=myexplode)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([10,30,25,35])
mylabels=["Ananas","Banan","Apple","Dates"]
myexplode=[0.2,0,0,0]
plt.pie(x,labels=mylabels,startangle=90,explode=myexplode,shadow=True)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([10,30,25,35])
mylabels=["Ananas","Banan","Apple","Dates"]
mycolors=["black","hotpink","b","#4CAF50"]
myexplode=[0.2,0,0,0]
plt.pie(x,labels=mylabels,startangle=90,explode=myexplode, colors=mycolors)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([10,30,25,35])
mylabels=["Ananas","Banan","Apple","Dates"]

plt.pie(x,labels=mylabels)
plt.legend()
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([10,30,25,35])
mylabels=["Ananas","Banan","Apple","Dates"]

plt.pie(x,labels=mylabels)
plt.legend(title='Four Fruits')
plt.show()